# Form implementation generated from reading ui file 'C:\Users\vipno\Documents\projects\GenerateCodeUseGPT\ui\settings.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(728, 221)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEditRootDir = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditRootDir.setObjectName("lineEditRootDir")
        self.horizontalLayout_2.addWidget(self.lineEditRootDir)
        self.pushButtonOpenFolder = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonOpenFolder.setObjectName("pushButtonOpenFolder")
        self.horizontalLayout_2.addWidget(self.pushButtonOpenFolder)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEditOpenAIKey = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditOpenAIKey.setObjectName("lineEditOpenAIKey")
        self.horizontalLayout_3.addWidget(self.lineEditOpenAIKey)
        self.pushButtonApplyOpenAIKey = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonApplyOpenAIKey.setObjectName("pushButtonApplyOpenAIKey")
        self.horizontalLayout_3.addWidget(self.pushButtonApplyOpenAIKey)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEditGooglePalmKey = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEditGooglePalmKey.setObjectName("lineEditGooglePalmKey")
        self.horizontalLayout_4.addWidget(self.lineEditGooglePalmKey)
        self.pushButtonApplyGooglePalmKey = QtWidgets.QPushButton(parent=Dialog)
        self.pushButtonApplyGooglePalmKey.setObjectName("pushButtonApplyGooglePalmKey")
        self.horizontalLayout_4.addWidget(self.pushButtonApplyGooglePalmKey)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Project Root Dir: "))
        self.pushButtonOpenFolder.setText(_translate("Dialog", "Open Folder..."))
        self.label_2.setText(_translate("Dialog", "OpenAI api-key:"))
        self.pushButtonApplyOpenAIKey.setText(_translate("Dialog", "Apply OpenAI api-key"))
        self.label_3.setText(_translate("Dialog", "Google PaLM api-key: "))
        self.pushButtonApplyGooglePalmKey.setText(_translate("Dialog", "Apply Google PaLM api-key"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
